"""add email at Company model

Revision ID: fd6bda13cf34
Revises: 079a7c6ddfd9
Create Date: 2025-11-12 04:13:33.258938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6bda13cf34'
down_revision = '079a7c6ddfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_companies_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_companies_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
